# Generated by Django 4.2.20 on 2026-07-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_customer_id',
            new_name='polar_customer_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_price_id',
            new_name='polar_product_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_subscription_id',
            new_name='polar_subscription_id',
        ),
    ]
