# Generated by Django 6.0.6 on 2026-07-01 19:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=2000)),
                ('monitor_type', models.CharField(choices=[('http', 'HTTP/HTTPS'), ('icmp', 'ICMP Ping'), ('port', 'TCP Port')], default='http', max_length=10)),
                ('check_interval', models.IntegerField(default=300)),
                ('timeout', models.IntegerField(default=10)),
                ('retries', models.IntegerField(default=3)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ssl_expiry_threshold', models.IntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('last_status', models.CharField(default='unknown', max_length=50)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('uptime_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='projects.project')),
            ],
            options={
                'db_table': 'monitors_monitor',
            },
        ),
    ]
