# Generated by Django 4.2.20 on 2026-07-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_monitorcheck_ssl_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monitorcheck',
            new_name='monitors_mo_monitor_7dd5e8_idx',
            old_name='monitors_mo_monitor_5a8f0d_idx',
        ),
    ]
